In [1]:
!git clone https://github.com/codewithpiyushh/Machine-learning-.git

Cloning into 'Machine-learning-'...


In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('train.csv')
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
df.dropna()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [ ]:
X = df.iloc[:,1:]
y =df.iloc[:,0]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
X_test_contiguous = np.ascontiguousarray(X_test)
y_pred = knn.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9648809523809524

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=200)

In [ ]:
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [ ]:
X_train_trf.shape

(33600, 200)

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(X_train_trf,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = knn.predict(X_test_trf)

In [ ]:
accuracy_score(y_test,y_pred)

0.9502380952380952

In [ ]:
for i in range(1,785):
  pca = PCA(n_components=1)
  X_train_trf = pca.fit_transform(X_train)
  X_test_trf = pca.transform(X_test)
  knn  = KNeighborsClassifier()
  knn.fit(X_train_trf,y_train)
  y_pred = knn.predict(X_test_trf)
  print(accuracy_score(y_test,y_pred))

0.2580952380952381
0.25952380952380955


KeyboardInterrupt: 

In [ ]:
pca = PCA(n_components=2)
X_train_trf = pca.fit_transform(X_train)
X_test_trf= pca.transform(X_test)

In [ ]:
X_train_trf

array([[-2.71869807, -0.48954359],
       [-0.67699632, -6.75349679],
       [-3.03319277,  6.50965922],
       ...,
       [ 2.14894921,  0.78011223],
       [ 1.05956524,  0.94800709],
       [17.70253883,  1.96225214]])

In [ ]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter(x=X_train_trf[:,0],
                 y=X_train_trf[:,1],
                 color =y_train_trf,
                 color_discrete_sequence=px.colors.qualitative.G10)
fig.show()

In [ ]:
pca = PCA(n_components=3)
X_train_trf = pca.fit_transform(X_train)
X_test_trf= pca.transform(X_test)

In [ ]:
X_train_trf

array([[-2.71864739, -0.48984426,  1.13513584],
       [-0.67703374, -6.75360759, -2.33702086],
       [-3.0332019 ,  6.50988105,  7.49253479],
       ...,
       [ 2.14881558,  0.78087895, -0.74748778],
       [ 1.0595796 ,  0.94765009,  3.94984709],
       [17.70259878,  1.96180802, -4.94339479]])

In [ ]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter_3d(x=X_train_trf[:,0],
                 y=X_train_trf[:,1],
                 z=X_train_trf[:,2],
                 color =y_train_trf,)
fig.update_layout(margin=dict(l=20,r=20,b=20))
fig.show()

In [ ]:
pca.explained_variance_
# these are eigen values

array([40.67111198, 29.170234  , 26.74459593])

In [ ]:
pca.components_.shape
# these are eigen vectors

(3, 784)

In [ ]:
# findint the optimal number of principle components
# ev = lambda

In [ ]:
pca.explained_variance_ratio_

array([0.05785192, 0.0414927 , 0.03804239])

In [ ]:
pca = PCA(n_components=None)
X_train_trf = pca.fit_transform(X_train)
X_test_trf= pca.transform(X_test)